# Similar to ImitateDemo, except that it only generates the program without executing it.
# This is useful for visualizing the program.

# The path to the bag file containing the demonstration. The file name is used as an ID for the demonstration in the database.
string bag_path
---
string error # Empty string on success, error message otherwise
---
