# Generates a program given a sequence of demo states (stored in DB and referenced by bag_path).
# After some planning and retiming, the robot will execute the program.

# The path to the bag file containing the demonstration. The file name is used as an ID for the demonstration in the database.
string bag_path
---
string error # Empty string on success, error message otherwise
---
