grasp_planner:
  debug: true

  # Scoring weights
  antipodal_grasp_weight: 3
  non_antipodal_grasp_weight: 1
  antipodal_collision_weight: 0
  non_antipodal_collision_weight: -1
  sq_wrist_distance_weight: -2000
  obstacle_collision_weight: -1000000

  # Termination criteria
  max_planning_iterations: 5
  max_translation_for_termination: 0.02
  max_rotation_for_termination: 0.1

  # Parameters for optimizing the orientation of the gripper
  yaw_range_degrees: 90
  yaw_resolution_degrees: 10
  roll_range_degrees: 120
  roll_resolution_degrees: 10
  pitch_range_degrees: 63
  pitch_resolution_degrees: 9
  antipodal_degrees: 15

  # How many iterations to try adjusting the gripper placement
  max_placement_iterations: 10
