grasp_planner:
  debug: false

  # Scoring weights
  antipodal_grasp_weight: 4
  non_antipodal_grasp_weight: 0.5
  antipodal_collision_weight: -15
  non_antipodal_collision_weight: -20
  sq_wrist_distance_weight: -4000
  obstacle_collision_weight: -100000
  future_pose_weight: 100

  #antipodal_grasp_weight: 0.0224
  #non_antipodal_grasp_weight: -0.00905
  #antipodal_collision_weight: -0.00393
  #non_antipodal_collision_weight: -0.886
  #sq_wrist_distance_weight: -0.814
  #obstacle_collision_weight: -100000
  #future_pose_weight: 1.417

  # Termination criteria
  max_planning_iterations: 5
  max_translation_for_termination: 0.02
  max_rotation_for_termination: 0.1

  # Leaf size when downsampling objects as grasp points
  leaf_size: 0.015

  # Parameters for optimizing the orientation of the gripper
  yaw_range_degrees: 90
  yaw_resolution_degrees: 10
  roll_range_degrees: 120
  roll_resolution_degrees: 10
  pitch_range_degrees: 360
  pitch_resolution_degrees: 5
  antipodal_degrees: 7

  # How many iterations to try adjusting the gripper placement
  max_placement_iterations: 10
  placement_step_scale: 0.5

  # How many random offsets to try to escape collision
  max_escape_attempts: 10
