task_imitation:
  object_inflation_size: 0.05 # How much to inflate each object's dimensions when doing collision checking, in meters

  # Object initialization
  size_ambiguity_threshold: 0.15 # 1 = ambiguous, 0 = not ambiguous. Defined as size difference of best object / size difference of other object.
  match_dim_tolerance: 0.04 # At least two out of three dimensions must match the model by this distance.

  follow_traj_distance_between_poses: 0.02 # The minimum distance between poses to imitate when following a trajectory. This helps filter noise from object tracking.
  cart_path_eef_threshold: 0.02 # The maximum step size between end effector positions when following a trajectory
  cart_path_jump_threshold: 4 # The jump_threshold for planning paths when following a trajectory (measured in joint space distance)
  slice_pause_duration: 1 # Amount of time, in seconds, to wait in between executing slices
  num_planning_tries: 10 # Number of times to attempt motion planning for poses
